set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(RPI_SYSROOT /opt/rpi-sysroot)

set(CMAKE_SYSROOT ${RPI_SYSROOT})
set(CMAKE_C_COMPILER aarch64-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER aarch64-linux-gnu-g++)

set(CMAKE_SYSROOT_LINK "${RPI_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH ${RPI_SYSROOT})

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(PKG_CONFIG_EXECUTABLE pkg-config)
set(ENV{PKG_CONFIG_SYSROOT_DIR} ${RPI_SYSROOT})
set(ENV{PKG_CONFIG_LIBDIR}
    ${RPI_SYSROOT}/usr/lib/aarch64-linux-gnu/pkgconfig:${RPI_SYSROOT}/usr/share/pkgconfig)

set(RPI_RPATH_LINK_FLAGS
    "-Wl,-rpath-link,${RPI_SYSROOT}/lib/aarch64-linux-gnu \
     -Wl,-rpath-link,${RPI_SYSROOT}/usr/lib/aarch64-linux-gnu"
)

set(CMAKE_EXE_LINKER_FLAGS_INIT "${RPI_RPATH_LINK_FLAGS}")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "${RPI_RPATH_LINK_FLAGS}")
set(CMAKE_MODULE_LINKER_FLAGS_INIT "${RPI_RPATH_LINK_FLAGS}")
